### ISSUE TITLE
W10 session 3 date error

### ISSUE THREAD

**Issue by americast** [acl-org/acl-2020-virtual-conference#522]
The date for workshop 10 session 3 should be July 10, and not July 9.

Ref: https://virtual.acl2020.org/workshop_W10.html

**Comment by tlikhit** [comment]
@americast Could you tell me the source? Just confirming because the workshop's website lists it to be on the 9th: https://sites.google.com/view/repl4nlp2020/schedule?authuser=0

**Comment by raosudha89** [comment]
@americast  You are right. The last session day should be July 10 (since we are using GMT to define the day and under PDT we have said -1d, see below). 

Live Session 3: July 9 (00:00-03:00 GMT / 17:00-20:00 PDT -1d)

I will fix this in the release going in tonight. Thanks for catching this.

**Comment by tlikhit** [comment]
Oh I thought you were referring to Session 3 under detailed schedule. You're right, thanks for catching this!

**Comment by americast** [comment]
@raosudha89 Yes, the `.csv` files are already updated in the repo, but the `.yml` file needs a fix. I have created a branch https://github.com/acl-org/acl-2020-virtual-conference-sitedata/pull/216 with a fix but we might need to incorporate localisation.

@tlikhit Yes, you may refer to https://acl2020.org/assets/pdfs/conference-handbook/handbook_UTC+0.pdf for times in GMT.

**Comment by raosudha89** [comment]
I implemented a dirty fix to temporarily fix times of W10 (and W20 which had a similar issue) : https://github.com/acl-org/acl-2020-virtual-conference/pull/527

But someone with a better understanding of add_local_tz function (https://github.com/acl-org/acl-2020-virtual-conference/blob/master/static/js/time-extend.js) should do a better fix.

**Comment by GuyAglionby** [comment]
The date is processed separately to the time for workshops - the code assumes all sessions are on the same day (see [here](https://github.com/acl-org/acl-2020-virtual-conference/blob/93564f2580052b059cd8ceb2f41c9750b2a197d9/miniconf/load_site_data.py#L570)), and only uses the individual sessions in `workshop.yml` to [extract the GMT time](https://github.com/acl-org/acl-2020-virtual-conference/blob/93564f2580052b059cd8ceb2f41c9750b2a197d9/miniconf/load_site_data.py#L578-L580). I think `add_local_tz` is working as intended.

#527 is probably simplest fix for now, though date localisation should probably be given a look at for upstream.

**Comment by hao-fang** [comment]
I created a new issue #534

**Comment by americast** [comment]
> I implemented a dirty fix to temporarily fix times of W10 (and W20 which had a similar issue) : #527
> 

Cool! But, would advancing the workshop by a minute be a better solution? That would still not be fool-proof however. :thinking:
